"""Firewall vendor hardware comparison data."""

VENDORS = {
    "paloalto": {
        "name": "Palo Alto Networks",
        "color": "#ff6b6b",
        "description": "Single-pass architecture (SP3) with dedicated hardware data-planes. Known for consistent performance under full threat inspection.",
        "highlights": [
            "PA-400, PA-800, PA-3400, PA-5400, PA-7000 series",
            "Custom networking & security processing chips",
            "PAN-OS with integrated AI-powered threat prevention",
        ],
    },
    "fortinet": {
        "name": "Fortinet (FortiGate)",
        "color": "#51cf66",
        "description": "Purpose-built ASICs (NP7, CP9, SP5) deliver some of the highest raw throughput numbers in the industry at competitive price points.",
        "highlights": [
            "FortiGate 40F\u201370000 series",
            "Security Processing Units (SPUs) offload crypto & IPS",
            "FortiOS with Security Fabric integration",
        ],
    },
    "cisco": {
        "name": "Cisco (Secure Firewall)",
        "color": "#6c8cff",
        "description": "Deep integration with the broader Cisco networking stack. Snort 3\u2013based IPS engine with Talos threat intelligence.",
        "highlights": [
            "Secure Firewall 1000, 3100, 4200, 9300 series",
            "Leverages Cisco Silicon One in newer models",
            "Firepower Threat Defense (FTD) or ASA image",
        ],
    },
    "checkpoint": {
        "name": "Check Point",
        "color": "#a78bfa",
        "description": "Consistent security management via SmartConsole. Quantum appliances range from small branch to hyperscale data-centre gateways.",
        "highlights": [
            "Quantum Spark 1500, Quantum 6000/7000/Maestro",
            "HyperFlow technology for scaling",
            "R81+ Gaia OS with ThreatCloud AI",
        ],
    },
    "sophos": {
        "name": "Sophos (XGS Series)",
        "color": "#ff922b",
        "description": "Xstream architecture with a dedicated hardware FastPath for accelerating trusted traffic, freeing CPU for deep inspection.",
        "highlights": [
            "XGS 87\u2013XGS 8500 series",
            "Dual-processor design (Xstream Flow Processor + x86 CPU)",
            "Sophos Firewall OS with Synchronized Security",
        ],
    },
}

HARDWARE_TIERS = {
    "entry": {
        "title": "Entry-Level / Branch Office",
        "subtitle": "Compact desktop appliances for small offices and branch deployments.",
        "columns": [
            "Vendor / Model",
            "Firewall Throughput",
            "Threat / NGFW Throughput",
            "Interfaces",
            "Form Factor",
        ],
        "rows": [
            {
                "vendor": "paloalto",
                "model": "PA-460",
                "fw_throughput": "5.2 Gbps",
                "ngfw_throughput": "2.4 Gbps (App-ID)",
                "interfaces": "8\u00d7GbE, 4\u00d7SFP",
                "form_factor": "Desktop",
            },
            {
                "vendor": "fortinet",
                "model": "FortiGate 60F",
                "fw_throughput": "10 Gbps",
                "ngfw_throughput": "1.0 Gbps (NGFW)",
                "interfaces": "10\u00d7GbE",
                "form_factor": "Desktop",
            },
            {
                "vendor": "cisco",
                "model": "Secure FW 1120",
                "fw_throughput": "3.0 Gbps",
                "ngfw_throughput": "1.5 Gbps (FTD)",
                "interfaces": "8\u00d7GbE",
                "form_factor": "Desktop",
            },
            {
                "vendor": "checkpoint",
                "model": "Quantum 1590",
                "fw_throughput": "2.8 Gbps",
                "ngfw_throughput": "0.7 Gbps (Full TI)",
                "interfaces": "8\u00d7GbE, Wi-Fi 6",
                "form_factor": "Desktop",
            },
            {
                "vendor": "sophos",
                "model": "XGS 126",
                "fw_throughput": "5.5 Gbps",
                "ngfw_throughput": "1.0 Gbps (Xstream)",
                "interfaces": "8\u00d7GbE",
                "form_factor": "Desktop",
            },
        ],
    },
    "midrange": {
        "title": "Mid-Range / Campus",
        "subtitle": "1U rack-mount appliances for medium-sized enterprises and campus edge deployments.",
        "columns": [
            "Vendor / Model",
            "Firewall Throughput",
            "Threat / NGFW Throughput",
            "Interfaces",
            "HA Support",
        ],
        "rows": [
            {
                "vendor": "paloalto",
                "model": "PA-3440",
                "fw_throughput": "30 Gbps",
                "ngfw_throughput": "14 Gbps (App-ID)",
                "interfaces": "12\u00d710G SFP+, 2\u00d725G, 2\u00d740G",
                "form_factor": "Active/Passive, A/A",
            },
            {
                "vendor": "fortinet",
                "model": "FortiGate 600F",
                "fw_throughput": "36 Gbps",
                "ngfw_throughput": "10 Gbps (NGFW)",
                "interfaces": "4\u00d725G, 16\u00d7GbE, 8\u00d7SFP+",
                "form_factor": "Active/Passive, A/A, FGCP",
            },
            {
                "vendor": "cisco",
                "model": "Secure FW 3130",
                "fw_throughput": "25 Gbps",
                "ngfw_throughput": "8 Gbps (FTD)",
                "interfaces": "8\u00d710G, 2\u00d725G, 8\u00d7GbE",
                "form_factor": "Active/Standby, A/A",
            },
            {
                "vendor": "checkpoint",
                "model": "Quantum 6700",
                "fw_throughput": "29 Gbps",
                "ngfw_throughput": "7 Gbps (Full TI)",
                "interfaces": "2\u00d740G, 8\u00d710G, 16\u00d7GbE",
                "form_factor": "ClusterXL A/A, A/S",
            },
            {
                "vendor": "sophos",
                "model": "XGS 4300",
                "fw_throughput": "40 Gbps",
                "ngfw_throughput": "9.5 Gbps (Xstream)",
                "interfaces": "8\u00d7SFP+, 2\u00d7SFP28, 8\u00d7GbE",
                "form_factor": "Active/Passive, A/A",
            },
        ],
    },
    "enterprise": {
        "title": "Enterprise / Data Centre",
        "subtitle": "High-performance chassis and multi-blade systems for large enterprise and service-provider environments.",
        "columns": [
            "Vendor / Model",
            "Firewall Throughput",
            "Threat / NGFW Throughput",
            "Max Interfaces",
            "Form Factor",
        ],
        "rows": [
            {
                "vendor": "paloalto",
                "model": "PA-5450",
                "fw_throughput": "150 Gbps",
                "ngfw_throughput": "70 Gbps (App-ID)",
                "interfaces": "Up to 48\u00d725G / 8\u00d7100G",
                "form_factor": "4U Chassis",
            },
            {
                "vendor": "fortinet",
                "model": "FortiGate 4400F",
                "fw_throughput": "800 Gbps",
                "ngfw_throughput": "70 Gbps (NGFW)",
                "interfaces": "12\u00d7100G, 18\u00d725G, 16\u00d710G",
                "form_factor": "3U Rack",
            },
            {
                "vendor": "cisco",
                "model": "Secure FW 4245",
                "fw_throughput": "110 Gbps",
                "ngfw_throughput": "45 Gbps (FTD)",
                "interfaces": "Up to 24\u00d725G / 4\u00d7100G",
                "form_factor": "2U Rack",
            },
            {
                "vendor": "checkpoint",
                "model": "Quantum 28000",
                "fw_throughput": "145 Gbps",
                "ngfw_throughput": "30 Gbps (Full TI)",
                "interfaces": "Up to 64\u00d710G / 16\u00d740G",
                "form_factor": "2U Rack",
            },
            {
                "vendor": "sophos",
                "model": "XGS 8500",
                "fw_throughput": "99 Gbps",
                "ngfw_throughput": "22 Gbps (Xstream)",
                "interfaces": "8\u00d7SFP28, 16\u00d7SFP+, 8\u00d7GbE",
                "form_factor": "2U Rack",
            },
        ],
    },
}

FEATURE_COMPARISON = {
    "columns": [
        "Capability",
        "paloalto",
        "fortinet",
        "cisco",
        "checkpoint",
        "sophos",
    ],
    "rows": [
        {
            "capability": "Processing Approach",
            "paloalto": "Single-pass parallel processing (SP3) with custom FPGA/ASIC",
            "fortinet": "Custom SPU ASICs (NP7, CP9) offloading from x86",
            "cisco": "x86-based with Cisco Silicon One in newer models",
            "checkpoint": "x86 with SecurityPowerEngine; Maestro hyperscale orchestrator",
            "sophos": "Dual-processor: Xstream Flow Processor (FPGA) + x86 CPU",
        },
        {
            "capability": "Operating System",
            "paloalto": "PAN-OS",
            "fortinet": "FortiOS",
            "cisco": "FTD (Snort 3) or ASA",
            "checkpoint": "Gaia OS (R81+)",
            "sophos": "Sophos Firewall OS (SFOS)",
        },
        {
            "capability": "Central Management",
            "paloalto": "Panorama",
            "fortinet": "FortiManager + FortiAnalyzer",
            "cisco": "Firepower Management Center (FMC) / CDO",
            "checkpoint": "SmartConsole / Smart-1 Cloud",
            "sophos": "Sophos Central",
        },
        {
            "capability": "Threat Intelligence",
            "paloalto": "WildFire, Advanced Threat Prevention (inline ML)",
            "fortinet": "FortiGuard Labs (AI/ML, sandboxing)",
            "cisco": "Cisco Talos + SecureX",
            "checkpoint": "ThreatCloud AI (60+ engines)",
            "sophos": "SophosLabs + Sophos X-Ops, Intelix sandboxing",
        },
        {
            "capability": "SD-WAN Built-In",
            "paloalto": "Yes (Prisma SD-WAN optional)",
            "fortinet": "Yes (included in FortiOS, ASIC-accelerated)",
            "cisco": "Yes (Meraki or Viptela integration)",
            "checkpoint": "Yes (Quantum SD-WAN)",
            "sophos": "Yes (Xstream SD-WAN)",
        },
        {
            "capability": "Zero Trust / SASE",
            "paloalto": "Prisma Access, GlobalProtect",
            "fortinet": "FortiSASE, ZTNA via FortiClient",
            "cisco": "Cisco+ Secure Connect, Duo integration",
            "checkpoint": "Harmony Connect, Identity Awareness",
            "sophos": "ZTNA via Sophos Central",
        },
        {
            "capability": "TLS Inspection",
            "paloalto": "Hardware-assisted (SSL decryption offload)",
            "fortinet": "CP9 ASIC-accelerated",
            "cisco": "Software-based on x86",
            "checkpoint": "CoreXL multi-core acceleration",
            "sophos": "Xstream Flow Processor hardware offload",
        },
        {
            "capability": "Ecosystem Lock-In",
            "paloalto": "Moderate \u2014 Cortex, Prisma suite",
            "fortinet": "Strong \u2014 Security Fabric across 50+ products",
            "cisco": "Strong \u2014 deep Cisco networking integration",
            "checkpoint": "Moderate \u2014 Infinity architecture",
            "sophos": "Moderate \u2014 Synchronized Security (endpoint heartbeat)",
        },
        {
            "capability": "Licensing Model",
            "paloalto": "Tiered bundles (Threat, DNS, URL, WildFire)",
            "fortinet": "FortiGuard bundles (UTM, Enterprise, NGFW)",
            "cisco": "Tiered (Essentials, Advantage, Premier)",
            "checkpoint": "Blade-based (per software blade)",
            "sophos": "Bundled (Standard, Xstream Protection)",
        },
    ],
}

TAKEAWAYS = [
    {
        "title": "Best Raw Throughput",
        "body": "Fortinet\u2019s custom ASIC approach delivers industry-leading throughput numbers, especially at the enterprise tier, often at lower cost-per-Gbps than competitors.",
        "vendor": "fortinet",
    },
    {
        "title": "Most Consistent Under Load",
        "body": "Palo Alto\u2019s single-pass architecture means enabling all security features has a smaller performance penalty than vendors who inspect traffic in multiple stages.",
        "vendor": "paloalto",
    },
    {
        "title": "Best for Cisco Shops",
        "body": "If your network already runs Cisco switches, routers, and ISE, the Secure Firewall integrates natively with your existing stack and Talos intelligence.",
        "vendor": "cisco",
    },
    {
        "title": "Strongest Central Management",
        "body": "Check Point\u2019s SmartConsole has long been regarded as one of the most mature multi-gateway management platforms, especially for complex rule bases.",
        "vendor": "checkpoint",
    },
    {
        "title": "Best Endpoint Synergy",
        "body": "Sophos Synchronized Security creates a real-time heartbeat between the firewall and endpoint, enabling automated lateral-movement isolation that other vendors require additional products to achieve.",
        "vendor": "sophos",
    },
    {
        "title": "SD-WAN Value",
        "body": "Fortinet includes full SD-WAN in FortiOS at no extra licence cost, with ASIC-accelerated overlay performance \u2014 often replacing a dedicated SD-WAN appliance.",
        "vendor": "fortinet",
    },
]
